// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../core/components/base/BaseButton/BaseButton.vue')['default']
    BaseInput: typeof import('./../core/components/base/BaseInput/BaseInput.vue')['default']
    HelloWorld: typeof import('./../core/components/HelloWorld.vue')['default']
  }
}

export { }
